#app.yml file src/main/appengine

runtime: java
env: flex

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud-gcp"

handlers:
  - url: /.*
  script: this field is required, but ignored
  secure: always
manual_scaling:
  instances: 1

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 10